 const ActionTypes = {
    USERNAME:'USERNAME',
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID' , 
    MOVIES: 'MOVIES'
}

export default ActionTypes;
